### ISSUE TITLE
Sin and cos give incorrect results?

### ISSUE THREAD

**Issue by akikoskinen** [Lokathor/wide#26]
I tried to use the `wide::sin_f32` and `wide::cos_f32` functions. I got some confusing results so I plotted some of the results. This plot shows the functions' results as well as the real sin and cos values on the interval -6.5..6.5 (about minus 2*pi to 2*pi):

![Wide sin and cos plot](https://uc3ae49df95aa917d08ac41d4ffe.previews.dropboxusercontent.com/p/thumb/AAybF_0CXn1y40w9FCfg7lS329J4OvfZwzFLSpB9zi90wANHiX22BRXumIPNaW3W9F1voSEQ0BAbnuvyiDm3q5DkCl3CM1wkFI9DtkK34OSpXr9LtxfsI4PlbTZcNcY0v-FfGLA03oX_yOT1CRf7cEMtU8yzMt4mpe0U3FAmP8Mp_rK_sJgd1g3QSRcgjm6RfdrVentabmUrjbUzuzBBOc6DvToWoMHAGY3JfAhP2MnRp3HAUO7uuTlqsd5E3ibWBC8t7R-iQ-ic-u2kFZqJ4MbYAB1XYkDkGvbpjF4iZjC31OS7rQAk09spiFoD84h3h-kilJzlLp38i2YoksVAeNG0AtxdDrkTfShzxVvZOHvIy56910dvtCUSPmUVGbdAqHo_E7YSKzb8t0zPv0v4AocT/p.png)

What gives?

**Comment by Lokathor** [comment]
Oh dag, I suppose there's a nasty formula error in there somewhere. It should be a tiny bit off at most, not _so clearly_ wrong.

I guess you're the first person to even notice this since I haven't touched the crate in ages and no one else has said anything.

We can just eliminate the "wideness" and go back to calling the intrinsic on each lane one at a time until someone has the time to dig into this. I'll put out a patch.

**Comment by Lokathor** [comment]
Okay, newly released `0.4.4` will give correct results, but it requires std now.

I'm gonna leave this open because it's still a problem to not have it run the calculations run in SIMD.
