### ISSUE TITLE
Zero dependency variant

### ISSUE THREAD

**Issue by RazrFalcon** [Lokathor/wide#58]
Currently, the crate has two dependencies, and for such a simple and low-level crate I would assumed that it should not have any dependencies at all. At least this is what I'm trying to do with my crates.

Would you be interested in removing all the dependencies?

**Comment by Lokathor** [comment]
The two dependencies provide vital `unsafe` operations with a safe interface.

Actually if you look in the git history you'll see that `safe_arch` used to be a part of this crate directly, but it was factored into its own crate so that the safe wrapping could all be put in one place and possibly others could use it as well.

Similarly, `bytemuck` used to be part of a larger crate, but it's so useful that it was placed in a small and self-contained crate of its own, where the unsafe code can be carefully audited and kept behind a safe interface.

Because of these crates, we're able to keep nearly all unsafe code out of `wide`, other than the impls of the `bytemuck` traits. This is a pretty good thing, and vendoring a copy of code from those crates into this crate wouldn't really gain us anything.
